 version: "3.7"

 services:
   app1:
     ports:
       - 5000:80
     working_dir: /usr/src/app
     volumes:
       - ./:/var/www/html
     build: .
     image: sbeltran2006/phpsimple
     profiles: 
      - dev

   app2:
     ports:
       - 5001:80
     working_dir: /usr/src/app
     volumes:
       - ./:/var/www/html
     build: .
     image: sbeltran2006/phpsimple
     profiles:
      - prod
