 version: "3.7"

 services:
   app1:
     ports:
       - 5000:80
     working_dir: /usr/src/app
     volumes:
       - ./:/var/www/html
     build: .
     image: sbeltran2006/phpsimple
     profiles: 
      - dev

   app2:
     ports:
       - 5001:80
     working_dir: /usr/src/app
     volumes:
       - ./:/var/www/html
     build: .
     image: sbeltran2006/phpsimple
     profiles:
      - prod

   db:
     image: mariadb:10.4
     volumes:
      - volumen1:/var/lib/mysql
     ports:
       - 3308:3306
     profiles:
       - dbprueba
     restart: always
     environment:
      MARIADB_ROOT_PASSWORD: example

      